# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11']
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: install deps
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install mypy pylint pylint-quotes pytest pytest-cov coveralls pytest-mock types-requests
      - name: Lint with mypy
        run: mypy .
      - name: Lint with pylint
        run: pylint instagram_archiver
